name: Publish NPM Package

on:
  push:
    tags:
      # This tag will never exist, so the workflow will never run
      # instead, the publish workflow that publishes to Auditorium's Github packages will run
      - 'this-tag-will-never-exist-123456789'

jobs:
  package:
    runs-on: ubuntu-latest
    name: Publish NPM Package

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: npm i
      - run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
